### ISSUE TITLE
Parenthesis Cause see() to return false 

### ISSUE THREAD

**Issue by tomwalsh** [laracasts/Integrated#24]
I was testing this and was surprised to find this bug, but I don't know if it belongs here or upstream or not.

```
public function test_delete_customer()
{
    $this->test_add_customer();
    $customer = User::where('username', '=', $this->newuser['username'])->firstOrFail();
    $this->visit('/admin/customers/' . $customer->id  )
        ->see('Customer Detail')
        ->click('Delete')
        ->onPage('/admin/customers')
        ->see('Customer ' . $customer->first_name . ' ' . $customer->last_name . ' (' .     $customer->id . ') has been deleted.');

    }
```

Was returning failed, even though the output indicated it was there and correct.

Changing the see() call to:

```
->see('Customer ' . $customer->first_name . ' ' . $customer->last_name . ' \(' . $customer->id . '\) has been deleted.');
```

Corrected the issue.

I think this might be an issue with accepted syntax of the PCRE and what see() is passing.

**Comment by bvangraafeiland** [comment]
That's because a regular expression is used for the `see()` method, and hence the parentheses are special characters. I'm not sure if this should be changed, because now you can also use regexps yourself.

**Comment by tomwalsh** [comment]
I realize that. Hence my comment about the syntax and PCRE. There should either be some documentation stating that, or special PCRE characters be filtered from the see() method, was more to the point of this issue report.

**Comment by EdRands** [comment]
I just encountered the same problem looking for a question on the page, because a ? has a special meaning in a regex.

To my way of thinking, see() should look for the actual string I pass it, not a regex interpretation of what I give it. Therefore I believe it should backslash escape any characters with special meanings - a simple preg_quote() does nicely - before doing the assertion.

If users have a need for such a thing, then I'd suggest a separate seeRegularExpression() function.

As it stands, I have to wrap my offending string in preg_quote() first.

**Comment by danwall** [comment]
I have been overriding the see() method in my TestCase.php to do this, so would love to see the referenced PR merged in.

``` php
public function see($text)
{
    return parent::see(preg_quote($text, '/'));
}
```
